/* Each student follows the requested format:
   Const EachStudents = [
     { examNum, name, class, gender }
   ]
*/
const Students = [
  { examNum: "SS1001", name: "Chukwuma Chuks", class: "SS1", gender: "Male" },
  { examNum: "SS1002", name: "Kelvin Evans", class: "SS1", gender: "Male" },
  { examNum: "SS1003", name: "Victoria Saro John", class: "SS1", gender: "Female" },
  { examNum: "SS1004", name: "Rejoice Eze", class: "SS1", gender: "Female" },
  { examNum: "SS1005", name: "Nwana Michael", class: "SS1", gender: "Female" },
  { examNum: "SS1006", name: "Nwindum Progress", class: "SS1", gender: "Female" },
  { examNum: "SS1007", name: "Florence Michael", class: "SS1", gender: "Female" },
  { examNum: "SS1008", name: "Justina Sunday", class: "SS1", gender: "Female" },
  { examNum: "SS1009", name: "Emmanuel Edanuko", class: "SS1", gender: "Male" },
  { examNum: "SS1010", name: "Harmony Michael", class: "SS1", gender: "Female" },
  { examNum: "SS1011", name: "Onuma Abigail", class: "SS1", gender: "Female" },
  { examNum: "SS1012", name: "Victor Francis", class: "SS1", gender: "Male" },
  { examNum: "SS1013", name: "Mercy James", class: "SS1", gender: "Female" },
  { examNum: "SS1014", name: "Goodluck Anene", class: "SS1", gender: "Male" },
  { examNum: "SS1015", name: "Favour Samuel", class: "SS1", gender: "Male" },
  { examNum: "SS1016", name: "Magdalena Francis", class: "SS1", gender: "Female" },
  { examNum: "SS1017", name: "Prince Ekruba", class: "SS1", gender: "Male" },
  { examNum: "SS1018", name: "Kingsley Blessing", class: "SS1", gender: "Female" },
  { examNum: "SS1019", name: "Abel Innocent", class: "SS1", gender: "Male" },
  { examNum: "SS1020", name: "Amarachi Edward", class: "SS1", gender: "Female" },
{ examNum: "SS1021", name: "Adekanmi Ganiyat", class: "SS1", gender: "Female" },
  { examNum: "SS1022", name: "Bright Saro Edee", class: "SS1", gender: "Male" },
  { examNum: "SS1023", name: "Treasure Evans", class: "SS1", gender: "Female" },
  { examNum: "SS1024", name: "Juliana Francis", class: "SS1", gender: "Female" },
  { examNum: "SS1025", name: "Agnes Joseph", class: "SS1", gender: "Female" },
   { examNum: "SS1026", name: "Winner Chinedu", class: "SS1", gender: "Female" },
  { examNum: "SS1027", name: "Shalom Okoi", class: "SS1", gender: "Female" },
  { examNum: "SS1028", name: "Kpuinem Treasure", class: "SS1", gender: "Female" },
  { examNum: "SS1029", name: "Gideon Ogbonda", class: "SS1", gender: "Male" },
  { examNum: "SS1030", name: "Emmanuel Okebata", class: "SS1", gender: "Male" },
  { examNum: "SS1031", name: "Precious George", class: "SS1", gender: "Female" },
  { examNum: "SS1032", name: "Miracle Onyekwere", class: "SS1", gender: "Female" },
  { examNum: "SS1033", name: "Success Onyeka", class: "SS1", gender: "Female" },
  { examNum: "SS1034", name: "Andrew Michael", class: "SS1", gender: "Male" },
  { examNum: "SS1035", name: "Queen Zorbari", class: "SS1", gender: "Female" },
  { examNum: "SS1036", name: "Faithfulness Ibe", class: "SS1", gender: "Female" },
  { examNum: "SS1037", name: "Femi Sunday", class: "SS1", gender: "Male" },
  { examNum: "SS1038", name: "Emmanuel Victoria", class: "SS1", gender: "Female" },
  { examNum: "SS1039", name: "Treasure Okechukwu", class: "SS1", gender: "Female" },
  { examNum: "SS1040", name: "Divine Ngalaka", class: "SS1", gender: "Female" },
  { examNum: "SS1B041", name: "John Peter", class: "SS1", gender: "Male" },
  { examNum: "SS1B042", name: "Grace Samuel", class: "SS1", gender: "Female" },
  { examNum: "SS1B043", name: "Aisha Bello", class: "SS1", gender: "Female" },
  { examNum: "SS1B044", name: "David Okoro", class: "SS1", gender: "Male" },
  { examNum: "SS1B045", name: "Favour Ude", class: "SS1", gender: "Female" },
{ examNum: "SS1B046", name: "John Peter", class: "SS1", gender: "Male" },
  { examNum: "SS1B047", name: "Grace Samuel", class: "SS1", gender: "Female" },
  { examNum: "SS1B048", name: "Aisha Bello", class: "SS1", gender: "Female" },
  { examNum: "SS1B049", name: "David Okoro", class: "SS1", gender: "Male" },
  { examNum: "Admin1", name: "**Result Checker**", class: "SS1", gender: "Male" }
  

  /* Add more students as needed */
];
