window.studentsSS2 = [
{ examNum: "SS2051", name: "Oluchi Chuks Omi", class: "SS2", gender: "Female" },
  { examNum: "SS2052", name: "First-Lady Ishaka", class: "SS2", gender: "Female" },
  { examNum: "SS2053", name: "Umusalamatu Yakubu", class: "SS2", gender: "Female" },
  { examNum: "SS2054", name: "Happiness Goodwin Etim", class: "SS2", gender: "Female" },
  { examNum: "SS2055", name: "Marcus George", class: "SS2", gender: "Male" },
  { examNum: "SS2056", name: "Peace Isaac Sunday", class: "SS2", gender: "Female" },
  { examNum: "SS2057", name: "Raphael Emmanuel", class: "SS2", gender: "Male" },
  { examNum: "SS2058", name: "Victoria Anayochukwu", class: "SS2", gender: "Female" },
  { examNum: "SS2059", name: "Simon Nwikpughi", class: "SS2", gender: "Male" },
  { examNum: "SS2060", name: "Akpan Miracle Dennis", class: "SS2", gender: "Female" },
  { examNum: "SS2061", name: "Wisdom Akpan Dennis", class: "SS2", gender: "Male" },
  { examNum: "SS2062", name: "Asuquo Charity", class: "SS2", gender: "Female" },
  { examNum: "SS2063", name: "Favour God's power", class: "SS2", gender: "Female" },
  { examNum: "SS2064", name: "Samuel Johnson", class: "SS2", gender: "Male" },
  { examNum: "SS2065", name: "Pat Elias Sharon", class: "SS2", gender: "Female" },
  { examNum: "SS2066", name: "Innocent Goodluck", class: "SS2", gender: "Male" },
  { examNum: "SS2067", name: "Oken Miracle", class: "SS2", gender: "Female" },
  { examNum: "SS2068", name: "Kosisochukwu Nora", class: "SS2", gender: "Female" },
  { examNum: "SS2069", name: "Promise Eze", class: "SS2", gender: "Male" },
  { examNum: "SS2070", name: "Favour Odeomena", class: "SS2", gender: "Female" },
{ examNum: "SS2071", name: "David Igwe", class: "SS2", gender: "Male" },
  { examNum: "SS2072", name: "Golden Korne", class: "SS2", gender: "Male" },
  { examNum: "SS2073", name: "Nwiko Dominion", class: "SS2", gender: "Female" },
  { examNum: "SS2074", name: "Emmanuella Olaka", class: "SS2", gender: "Female" },
  { examNum: "SS2075", name: "Success Adaugo", class: "SS2", gender: "Female" },
   { examNum: "SS2076", name: "James Precious Akachi", class: "SS2", gender: "Female" },
  { examNum: "SS2077", name: "Favour Nwafor", class: "SS2", gender: "Female" },
  { examNum: "SS2078", name: "Adolphus Ngalaka", class: "SS2", gender: "Male" },
  { examNum: "SS2079", name: "Sinaza Faith", class: "SS2", gender: "Female" },
  { examNum: "SS2080", name: "Moses Samuel", class: "SS2", gender: "Male" },
  { examNum: "SS2081", name: "Emmanuel James", class: "SS2", gender: "Male" },
  { examNum: "SS2082", name: "Joy Aniefok", class: "SS2", gender: "Female" },
  { examNum: "SS2083", name: "Zini Emmanuel", class: "SS2", gender: "Male" },
  { examNum: "SS2B084", name: "David Okoro", class: "SS2", gender: "Male" },
  { examNum: "SS2B085", name: "Favour Ude", class: "SS2", gender: "Female" },
  { examNum: "SS2B086", name: "John Peter", class: "SS2", gender: "Male" },
  { examNum: "SS2B087", name: "Grace Samuel", class: "SS2", gender: "Female" },
  { examNum: "SS2B088", name: "Aisha Bello", class: "SS2", gender: "Female" },
  { examNum: "Admin", name: "Sir Bright", class: "SS2", gender: "Male" },
  { examNum: "Admin2", name: "Sir Sunday", class: "SS2", gender: "Male" }
  
  

  /* Add more students as needed */
];