window.questionsSS3 = {
    //Mathematics
  Mathematics: [
    { id: "m1", text: "Differentiate f(x)=x^2", img: null, options: ["2x","x","x^2","1"], answer: 0 },
    { id: "m2", text: "Integrate ∫2 dx", img: null, options: ["2x + C", "x^2 + C", "ln x + C", "1/x + C"], answer: 0 },
{ id: "m3", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m4", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m5", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m6", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m7", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m8", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m9", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m10", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m11", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m12", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m13", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m14", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m15", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m16", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m17", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m18", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m19", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m20", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m21", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m22", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m23", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m24", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
  { id: "m25", text: "What is 8 + 7?", img: null, options: ["12","14","15","16"], answer: 2 },
    { id: "m26", text: "Find the value of x: 2x + 3 = 11", img: null, options: ["3","4","5","6"], answer: 1 },
    { id: "m27", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m28", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 },
    { id: "m29", text: "What is the perimeter of a rectangle with sides 3 and 5?", img: null, options: ["8","16","15","10"], answer: 1 },
    // sample with image (math diagram)
    { id: "m30", text: "Identify the angle marked 'x' in the figure.", img: "images/recomella.png", options: ["30°","45°","60°","90°"], answer: 2 }
  ],


  //English Language
  English: [
    { id: "e1", text: "Choose correct preposition: 'She is good ___ math.'", img: null, options: ["on","at","in","about"], answer: 1 },
  { id: "e2", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e3", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e4", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e5", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e6", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
{ id: "e7", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e8", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e9", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e10", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e11", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e12", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
{ id: "e13", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e14", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e15", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e16", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e17", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e18", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
{ id: "e19", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e20", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e21", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e22", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e23", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e24", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
{ id: "e25", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e26", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e27", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e28", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 },
    { id: "e29", text: "Choose the correct plural of 'child'.", img: null, options: ["childs","childes","children","child"], answer: 2 },
    { id: "e30", text: "Pick the correct verb: 'She ___ to school daily.'", img: null, options: ["go","goes","gone","going"], answer: 1 }
  ],


  //Physics
  Physics: [
    { id: "p1", text: "The unit of energy is?", img: null, options: ["Newton","Watt","Joule","Meter"], answer: 2 },
 { id: "p2", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p3", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p4", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p5", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p6", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
{ id: "p7", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p8", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p9", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p10", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p11", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p12", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
{ id: "p13", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p14", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p15", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p16", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p17", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p18", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
{ id: "p19", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p20", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p21", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p22", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p23", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p24", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
{ id: "p25", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p26", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p27", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p28", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p29", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
 { id: "p30", text: "Which is the SI unit of force?", img: null, options: ["Joule","Newton","Watt","Pascal"], answer: 1 }
  ],


  //Chemistry
  Chemistry: [
    { id: "c1", text: "An atom contains?", img: null, options: ["Only protons", "Protons & electrons", "Neutrons only", "None"], answer: 1 },
 { id: "c2", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c3", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c4", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c5", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c6", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c7", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c8", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c9", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c10", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c11", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c12", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c13", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c14", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c15", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c16", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c17", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c18", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c19", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c20", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c21", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c22", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c23", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c24", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c25", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c26", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c27", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c28", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 },
{ id: "c29", text: "Water is a compound of?", img: null, options: ["Hydrogen and Oxygen", "Carbon & Oxygen", "Nitrogen & Hydrogen", "Helium & Neon"], answer: 0 },
    { id: "c30", text: "Which is a symbol for Oxygen?", img: null, options: ["O","Ox","Og","On"], answer: 0 }
  ],


  //Biology
  Biology: [
    { id: "b1", text: "DNA stands for?", img: null, options: ["Deoxyribo Nucleic Acid","Deoxy Nerve Acid","None","Dioxo Acid"], answer: 0 },
{ id: "b2", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b3", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b4", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b5", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b6", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b7", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b8", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b9", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b10", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b11", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b12", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b13", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b14", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b15", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b16", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b17", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b18", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b19", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b20", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b21", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b22", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b23", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b24", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b25", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b26", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b27", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b28", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b29", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 },
{ id: "b30", text: "Which organ pumps blood?", img: null, options: ["Lung","Kidney","Heart","Liver"], answer: 2 }
  ],


  //Economics
  Economics: [
    { id: "ec1", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec2", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec3", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec4", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec5", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
    { id: "ec6", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec7", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec8", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec9", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec10", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
    { id: "ec11", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec12", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec13", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec14", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec15", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
    { id: "ec16", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec17", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec18", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec19", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 },
 { id: "ec20", text: "Demand increases when price", img: null, options: ["Increases","Falls","Stays same","None"], answer: 1 }
  ],


//Geography
  Geography: [
    { id: "g1", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g2", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g3", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g4", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g5", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
 { id: "g6", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g7", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g8", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g9", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g10", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
 { id: "g11", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g12", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g13", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g14", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g15", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
 { id: "g16", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g17", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g18", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g19", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ id: "g20", text: "The largest ocean is?", img: null, options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 }
  ],


  //Computer Science
  ComputerScience: [
{ id: "co1", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co2", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co3", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co4", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co5", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co6", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co7", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co8", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co9", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co10", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co11", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co12", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co13", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co14", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co15", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co16", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co17", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co18", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co19", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 },
{ id: "co20", text: "Which of this is an input device", img: null, options: ["Monitor","Printer","Mouse","Speaker"], answer: 2 }
  ],


  //Data Processing
  DataProcessing: [
{ id: "dp1", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp2", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp3", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp4", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp5", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp6", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp7", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp8", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp9", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp10", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp11", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp12", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp13", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp14", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp15", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp16", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp17", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp18", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp19", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 },
{ id: "dp20", text: "Which of this is not a computing device", img: null, options: ["Fridge","Palmtop","Laptop","Desktop"], answer: 0 }
  ],


  //Civic Education
  CivicEducation: [
    { id: "cv1", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv2", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv3", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv4", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv5", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
 { id: "cv6", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv7", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv8", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv9", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv10", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
 { id: "cv11", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv12", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv13", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv14", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv15", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
 { id: "cv16", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv17", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv18", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv19", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 },
{ id: "cv20", text: "A democratic government is chosen by?", img: null, options: ["Monarch","Elections","Force","Lottery"], answer: 1 }
  ]
};